@startuml
class Person{
-name : String
-dateBirth: Int
-telephone: Int
-cpf: Int
--
+calculateAge()
+checkCPF()
}

class User extends Person{
-id: Int
-height: Double
-weight: Double

}
class TrainingPlan{
-objective: String
-durationWeeks: Double
}


class Trainer extends Person{
-specialty: String
-experienceYears: Int
-availability : String
}

class TypeExercise{
-upperLimbs
-breastplate
-back
-lowerLimbs
-core
--
+checkTrainer()
}

class Exercises{
-user: User
-typeExercise : TypeExercise
-trainingPlan: TrainingPlan
--
+calculateRepetitions()
+calculateIMC()
}



Exercises <-* TypeExercise
Exercises <--* TrainingPlan
Exercises <--* User
@enduml